repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml, --install-types, --non-interactive, --ignore-missing-imports, app]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, app]
        exclude: ^tests/

  - repo: local
    hooks:
      - id: uv-sync
        name: UV Sync
        entry: uv sync
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual]

      - id: test
        name: Run Tests
        entry: uv run pytest tests/ --tb=short
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual]

      - id: security-check
        name: Security Check
        entry: uv run safety check
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual]
